export default {
	ACCOUNT: {
		CHECK_USER_PLAN: {
			GET: 'GET_CHECK_USER_PLAN',
			GET_SUCCESS: 'GET_CHECK_USER_PLAN_SUCCESS',
			GET_ERROR: 'GET_CHECK_USER_PLAN_ERROR',
		},
	},
	APP: {
		GET_INFO: 'GET_APP_INFO',
		GET_INFO_SUCCESS: 'GET_APP_INFO_SUCCESS',
		GET_INFO_ERROR: 'GET_APP_INFO_ERROR',
		GET_MAPPINGS: 'GET_APP_MAPPINGS',
		GET_MAPPINGS_SUCCESS: 'GET_APP_MAPPINGS_SUCCESS',
		GET_MAPPINGS_ERROR: 'GET_APP_MAPPINGS_ERROR',
		GET_CREDENTIALS: 'GET_APP_CREDENTIALS',
		GET_CREDENTIALS_SUCCESS: 'GET_APP_CREDENTIALS_SUCCESS',
		GET_CREDENTIALS_ERROR: 'GET_APP_CREDENTIALS_ERROR',
		PERMISSION: {
			GET: 'GET_APP_PERMISSION',
			GET_SUCCESS: 'GET_APP_PERMISSION_SUCCESS',
			GET_ERROR: 'GET_APP_PERMISSION_ERROR',
			CREATE: 'CREATE_APP_PERMISSION',
			CREATE_SUCCESS: 'CREATE_APP_PERMISSION_SUCCESS',
			CREATE_ERROR: 'CREATE_APP_PERMISSION_ERROR',
			DELETE: 'DELETE_APP_PERMISSION',
			DELETE_SUCCESS: 'DELETE_APP_PERMISSION_SUCCESS',
			DELETE_ERROR: 'DELETE_APP_PERMISSION_ERROR',
			UPDATE: 'UPDATE_APP_PERMISSION',
			UPDATE_SUCCESS: 'UPDATE_APP_PERMISSION_SUCCESS',
			UPDATE_ERROR: 'UPDATE_APP_PERMISSION_ERROR',
		},
	},
};
